# Generated by Django 5.1.3 on 2025-03-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LockIn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
        migrations.AddField(
            model_name='tasks',
            name='required_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
