# Generated by Django 5.1.3 on 2025-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LockIn', '0002_remove_tasks_completed_tasks_required_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
